FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

 ENV PATH="$PATH:/root/.dotnet/tools"

 RUN dotnet tool install dotnet-roundhouse -g --version 1.3.1

WORKDIR .
COPY sql/ ./sql/
# Uncomment if you need to insert the test data
# COPY tests/IntegrationTest/sql/runFirstAfterUp ./sql/runFirstAfterUp

ENTRYPOINT [ "rh", "--connectionstring=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=assettable_34e5ee62429c4724b3d03891bd0a08c9;Pooling=true", "--connstringadmin=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=postgres;Pooling=true", "--sqlfilesdirectory=sql", "--environmentnames=DEV01", "--databasetype=postgres","--silent","--wt=true" ]