alter table columns alter column id drop identity;
alter table columns alter column id add generated by default as identity;
select setval('columns_id_seq', coalesce((select max(id)+1 from columns), 1), false);
